export const envConfig = {
  GOOGLE_RECAPTCHA_SITE_KEY: import.meta.env.VITE_GOOGLE_RECAPTCHA_SITE_KEY,
  GOOGLE_RECAPTCHA_SECRET_KEY: import.meta.env.VITE_GOOGLE_RECAPTCHA_SECRET_KEY,
  GOOGLE_RECAPTCHA_SITE_TEST_KEY: import.meta.env
    .VITE_GOOGLE_RECAPTCHA_SITE_TEST_KEY,
};
